config:
  sphere:
    calculation:
      ad_factor: 20
      rad_factor: 1
    display:
      frequency: 20
      duration: 400

  threads:
    particles_per_thread: 2147483647
    calculation_info: false

  particle:
    particle_type: VILLAGER_HAPPY
    particle_data:
      color:
        r: 0
        g: 0
        b: 0
      size: 1.0

messages:
  prefix: "&7[&5CTRZ&7] &b:"
  import: "%prefix% &aImport completed!"
  reload: "%prefix% &aReload completed!"
  invalid_number_args: "%prefix% &cInvalid number of arguments."
  invalid_argument: "%prefix% &cInvalid argument &9%arg%&c."
  no_permission: "&cNo permission."

config_version: 4